return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile" },
		opts = {
			ensure_installed = {
				"bash",
				"c",
				"cpp",
				"html",
				"markdown",
				"javascript",
				"typescript",
				"json",
				"css",
				"python",
				"lua",
				"luadoc",
				"diff",
				"markdown_inline",
				"query",
				"vim",
				"vimdoc",
				"regex",
				"sql",
				"dockerfile",
				"toml",
				"go",
				"gitignore",
				"yaml",
				"make",
				"cmake",
				"tsx",
			},
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
			autopairs = { enable = true },
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
}
